version: '3'

services:
  # =======================
  # NATS Server
  # =======================
  nats-server:
    image: nats:latest
  # =======================
  # CLIENT GATEWAY
  # =======================
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    # nombrar la imagen
    image: northamerica-south1-docker.pkg.dev/tienda-microservices-444410/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222
  # =======================
  # PRODUCTS Microservice
  # =======================
  products-ms:
    build:
      context: ./products-ms
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/tienda-microservices-444410/image-registry/products-ms
    environment:
      - PORT=3001
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=nats://nats-server:4222
  # =======================
  # ORDERS Microservice
  # =======================
  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: Dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: northamerica-south1-docker.pkg.dev/tienda-microservices-444410/image-registry/orders-ms
    environment:
      - PORT=3000
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222
  # =======================
  # PAYMENTS Microservice
  # =======================
  payments-ms:
    container_name: payments-ms
    build:
      context: ./payments-ms
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/tienda-microservices-444410/image-registry/payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
  # =======================
  # AUTH Microservice
  # =======================
  auth-ms:
    container_name: auth-ms
    build:
      context: ./auth-ms
      dockerfile: Dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/tienda-microservices-444410/image-registry/auth-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
